=== verilylifesciences/medtimeline/docs/assets/clinical_concept_configuration/clinical_concept_schema.json
{
    "$id": "clinical_concept_schema",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Clinical Concept",
    "type": "object",
    "required": [
        "codeString",
        "displayName"
    ],
    "additionalProperties": false,
    "properties": {
        "codeString": {
            "type": "string",
            "description": "The code (ex: LOINC, RxNorm) for this clinical concept."
        },
        "displayName": {
            "type": "string",
            "description": "The display name for this clinical concept, as returned by the FHIR server."
        },
        "showByDefault": {
            "description": "Whether this clinical concept should be displayed by default. False if unset.",
            "type": "boolean"
        },
        "displayBounds": {
            "type": "object",
            "required": [
                "lower",
                "upper"
            ],
            "properties": {
                "lower": {
                    "description": "Lower display bound for this concept. If unset, will be calculated based on data.",
                    "type": "number"
                },
                "upper": {
                    "description": "Upper display bound for this concept. If unset, will be calculated based on data.",
                    "type": "number"
                }
            }
        },
        "forceDisplayBounds": {
            "type": "boolean",
            "description": "Whether the display bounds should be forced even if the data is outside of them. No effect if displayBounds are unset. False if this is unset."
        },
        "groupName": {
            "type": "string",
            "description": "If set, this clinical concept will appear grouped with the same groupName. If unset, it will appear independently."
        },
        "innerComponentOnly": {
          "type": "boolean",
          "description": "If set, the ResourceCode for this component will be created, but it will not be displayed unless it is an inner component of another Resource."
        },
        "_comments": {
          "type": "string",
          "description": "Optional comments about the clinical concept"
        }
    }
}

=== verilylifesciences/medtimeline/medtimeline/src/assets/clinical_concept_configuration/vital_signs.json
[
  {
    "codeString": "8310-5",
    "displayName": "Temperature",
    "showByDefault": true,
    "displayBounds": {
      "lower": 35,
      "upper": 41
    }
  },
  {
    "codeString": "8867-4",
    "displayName": "Heart Rate",
    "showByDefault": true,
    "displayBounds": {
      "lower": 20,
      "upper": 300
    }
  },
  {
    "codeString": "9279-1",
    "displayName": "Respiratory Rate",
    "showByDefault": true,
    "displayBounds": {
      "lower": 6,
      "upper": 100
    }
  },
  {
    "codeString": "59408-5",
    "displayName": "Oxygen Saturation (SpO2)",
    "showByDefault": true,
    "displayBounds": {
      "lower": 5,
      "upper": 100
    },
    "forceDisplayBounds": true
  },
  {
    "codeString": "8462-4",
    "displayName": "Diastolic Blood Pressure",
    "showByDefault": true,
    "displayBounds": {
      "lower": 25,
      "upper": 150
    }
  },
  {
    "codeString": "8480-6",
    "displayName": "Systolic Blood Pressure",
    "showByDefault": true,
    "displayBounds": {
      "lower": 30,
      "upper": 250
    }
  },
  {
    "codeString": "41904-4",
    "displayName": "Blood Pressure Location",
    "showByDefault": true,
    "groupNames": [
      "Blood Pressure Details"
    ]
  },
  {
    "codeString": "55284-4",
    "displayName": "Blood Pressure",
    "showByDefault": true,
    "groupNames": [
      "Blood Pressure"
    ]
  },
  {
    "codeString": "8478-0",
    "displayName": "Mean Arterial Pressure (Device)",
    "showByDefault": true,
    "displayBounds": {
      "lower": 25,
      "upper": 200
    },
    "groupNames": [
      "Blood Pressure"
    ]
  }
]
